apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: soonie-tls-secret
spec:
  secretName: soonie-tls-secret
  dnsNames:
  - dsnacorp.com
  - www.dsnacorp.com
  - soonie.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dsnacorp.com
      - www.dsnacorp.com
      - soonie.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer